export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const CHANGE_ADMIN_TYPE = 'CHANGE_ADMIN_TYPE';
export const CHANGE_CURRENT_ADMIN_TYPE = 'CHANGE_CURRENT_ADMIN_TYPE';
export const AUTHENTICATE = 'AUTHENTICATE';
export const DEAUTHENTICATE = 'DEAUTHENTICATE';